In [2]:
import numpy as np


In [3]:
# Create a vector as row
vector_row = np.array([1,2,3])
print(vector_row) 

[1 2 3]


In [6]:
# Creating a vector as column
vector_column = np.array([[1],[4],[6]])
print(vector_column)

[[1]
 [4]
 [6]]


In [7]:
# Creating a matrix
matrix = np.array([[1,2],[3,4],[5,6]])
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
# Alternating way to create a matrix
matrix_object = np.mat([[1,2],[3,4],[5,6]])
print(matrix_object)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
# Creating a Sparse Matrix
# import numpy as np
"""A frequent situation in machine learning is having a huge amount of data; however,
most of the elements in the data are zeros. For example, imagine a matrix where the
columns are every movie on Netflix, the rows are every Netflix user, and the values
are how many times a user has watched that particular movie. This matrix would
have tens of thousands of columns and millions of rows! However, since most users
do not watch most movies, the vast majority of elements would be zero.
Sparse matrices only store nonzero elements and assume all other values will be zero,
leading to significant computational savings.We created a NumPy
array with two nonzero values, then converted it into a sparse matrix. If we view the
sparse matrix we can see that only the nonzero values are stored """
from scipy import sparse
matrix = np.array([[0,0],[0,1],[3,0]])
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [11]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
# View original sparse matrix
print(matrix_sparse)
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3
  (1, 1)	1
  (2, 0)	3


In [19]:
# Selecting Elements
# in both vector and matrix
vector = np.array([1,2,3,4,5,6,7])
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# Select third element of vector
print(vector[2])

#Select second row, second column
print(matrix[1,1])

# Select all elements of a vector
print(vector[:])

# Select everything up to and including the third element
print(matrix[:3])

# Select everything after the third element
print(vector[3:])

# Select the last element
print(vector[-1])

# Select the first two rows and all columns of a matrix
print(matrix[:2,:])

# Select all rows and the second column
print(matrix[:,1:2])

# Reverse of the Vector
print(vector[::-1])

# Revrese of the Matrix
print(matrix[::-1])

3
5
[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6 7]
7
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]
[7 6 5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [20]:
# Describing a Matrix
matrix = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
# View number of rows and columns
print(matrix.shape)

# View number of elements (rows * columns)
print(matrix.size)

# View number of dimensions
print(matrix.ndim)

(3, 4)
12
2


In [22]:
# Applying Operations to Elements

"""NumPy’s vectorize class converts a function into a function that can apply to all ele‐
ments in an array or slice of an array. It’s worth noting that vectorize is essentially a
for loop over the elements and does not increase performance. Furthermore, NumPy
arrays allow us to perform operations between arrays even if their dimensions are not
the same (a process called broadcasting)."""

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
print(vectorized_add_100(matrix))

# Using Broadcasting method directly which is a numpy advantage function
print(matrix + 100)


[[101 102 103]
 [104 105 106]
 [107 108 109]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [23]:
#Finding the Maximum and Minimum Values
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Return maximum element
print(np.max(matrix))

# Return minimum element
print(np.min(matrix))

""" we want to know the maximum and minimum value in an array or subset of an
array. This can be accomplished with the max and min methods. Using the axis
parameter we can also apply the operation along a certain axis"""

# Find maximum element in each column
print(np.max(matrix, axis=0))

# Find minimum element in each row
print(np.min(matrix,axis =1))

9
1
[7 8 9]
[1 4 7]


In [24]:
#Calculating the Average, Variance, and Standard Deviation

matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
# Return mean
print(np.mean(matrix))

# Return varience
print(np.var(matrix))

# Return standard deviation
print(np.std(matrix))

# Find the mean value for each column
print(np.mean(matrix,axis=0))

# Find the standard deviation for each row
print(np.std(matrix,axis=1))

5.0
6.666666666666667
2.581988897471611
[4. 5. 6.]
[0.81649658 0.81649658 0.81649658]


In [27]:
# Reshaping Arrays
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
# Reshape matrix into 2x6 matrix
print(matrix.reshape(2,6))

# Checking the size of the matrix
print(matrix.size)

"""One useful argument in reshape is -1, which effectively means “as many as needed,”
so reshape(-1, 1) means one row and as many columns as needed or simply FLATTEN a matrix"""

print(matrix.reshape(1,-1))
print(matrix.flatten())

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
12
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
#Transposing a Vector or Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Transpose matrix
print(matrix.T)

# Transpose vector
print(np.array([1,2,3,4,5,6,7]).T)

# Transposing row vector
print(np.array([[1, 2, 3, 4, 5, 6]]).T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[1 2 3 4 5 6 7]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [29]:
# Finding the Rank of a Matrix
matrix = np.array([[1, 1, 1],
                  [1, 1, 10],
                  [1, 1, 15]])

# Returning matrix rank
print(np.linalg.matrix_rank(matrix))

2


In [31]:
# Calculating the Determinant
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return determinant of matrix
print(np.linalg.det(matrix))

0.0


In [33]:
# Getting the Diagonal of a Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return diagonal elements
print(matrix.diagonal())

"""NumPy makes getting the diagonal elements of a matrix easy with diagonal. It is also
possible to get a diagonal off from the main diagonal by using the offset parameter."""

# Return diagonal one above the main diagonal
print(matrix.diagonal(offset=1))

# Return diagonal one below the main diagonal
print(matrix.diagonal(offset=-1))

[1 5 9]
[2 6]
[4 8]


In [35]:
# Calculating the Trace of a Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return Trace
print(matrix.trace())

""" trace of a matrix is the sum of the diagonal elements"""

# Return diagonal and sum elements
print(sum(matrix.diagonal()))

15
15


In [36]:
# Finding Eigenvalues and Eigenvectors
matrix = np.array([[1, -1, 3],
                  [1, 1, 6],
                  [3, 8, 9]])

# Caclulate eigenvalues and eigenvectors 
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# view eigenvalues
print(eigenvalues)

# view eigenvectors
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [38]:
# Calculating Dot Products

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
print(np.dot(vector_a,vector_b))

"""we can use the new @ operator"""

print(vector_a @ vector_b)

32
32


In [39]:
# Adding and Subtracting Matrices

# Creating Matrix A and Matrix B
matrix_a = np.array([[1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                    [1, 3, 1],
                    [1, 3, 8]])

# Adding two matrices
print(np.add(matrix_a,matrix_b))

print(matrix_a + matrix_b)

# Subtract two matrices
print(np.subtract(matrix_a, matrix_b))

print(matrix_a - matrix_b)

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [41]:
#  Multiplying Matrices
matrix_a = np.array([[1, 1],
                     [1, 2]])
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
print(np.dot(matrix_a,matrix_b))

""" Using @ operator too we can do matrix multiplication"""
print(matrix_a @ matrix_b)

""" we want to do element-wise multiplication, we can use the * operator"""
print(matrix_a * matrix_b)

[[2 5]
 [3 7]]
[[2 5]
 [3 7]]
[[1 3]
 [1 4]]


In [43]:
# Inverting a Matrix
matrix = np.array([[1, 4],
                   [2, 5]])

# Calculate inverse of matrix
print(np.linalg.inv(matrix))

"""The inverse of a square matrix, A, is a second matrix A–1, such that:
AA−1 = I
where I is the identity matrix. In NumPy we can use linalg.inv to calculate A–1 if it
exists. To see this in action, we can multiply a matrix by its inverse and the result is
the identity matrix"""

print(matrix @ np.linalg.inv(matrix))

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


In [45]:
# Generating Random Values

""" It can sometimes be useful to return the same random numbers multiple
times to get predictable, repeatable results. We can do this by setting the “seed” (an
integer) of the pseudorandom generator. Random processes with the same seed will
20 | Chapter 1: Vectors, Matrices, and Arrays
always produce the same output. """
# Set seed
np.random.seed(0)

# Generate three random floats between 0.0 and 1.0
print(np.random.random(3))

# Generate three random integers between 1 and 10
print(np.random.randint(0,11,3))

""" we can generate numbers by drawing them from a distribution"""

# Draw three numbers from a normal distribution with mean 0.0 and standard deviation of 1.0
print(np.random.normal(0.0,1.0,3))

# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
print(np.random.logistic(0.0,1.0,3))

# Draw three numbers greater than or equal to 1.0 and less than 2.0
print(np.random.uniform(1.0,2.0,3))

[0.5488135  0.71518937 0.60276338]
[3 7 9]
[-1.42232584  1.52006949 -0.29139398]
[-0.98118713 -0.08939902  1.46416405]
[1.47997717 1.3927848  1.83607876]
